src/index.css
Otherwise, when the window is not wide, the table stretches beyond the page width.
This also explicitly sets a few column widths to keep them from eating up whitespace and making other columns wrap.
=> Avoid stretching the table for filter inputs

src/components/Tickets/AddProject.js, src/components/Tickets/StartTimer.js, src/components/Tickets/Table.js, src/components/Tickets/ToggleProjects/Projects.js, src/index.css
This PR changes the Toggl start workflow. Currently, there are two ways to start a timer: click the large "Start" button, which begins a timer with the title of the ticket as the description; or click the small down arrow to reveal an empty description text field.
My proposal here is to remove the first option and simply pre-populate the text field with the default description. We _want_ users to provide a custom description more often than not. If one wants to keep the default, it's still possible.
I've also moved the input to a larger textarea to encourage users to write long-form descriptions of their work.
Minor changes:
* 693fe6a changes the table header "Resources" to "Assigned." This is a more intuitive title in my opinion.
* b28a2c4 adds a placeholder to the manual ID entry field …
=> Toggl description UX

src/components/Tickets/Table.js, src/index.css
Satisfies my desire for colored table rows - https://github.com/nadavspi/UnwiseConnect/issues/17
Color rows that are near or over budget for easy visibility. Color is OOB bootstrap danger & warning. Warning (yellow) gets applied when ticket actual is 90% or more of budget. If Budget is 0 no color is applied as that's considered `undefined`.
=> Add class to ticket row if budget is close to exceed or exceeded budget

src/actions/tickets.js
Use a sort method similar to what is used by version compare libraries.
The sort occurs only during the initial ticket load.
Screenshot of tickets sorted by wbsCode with wbsCode and dateEntered
columns added for illustration only.
Fixes #33
=> Sort Project Tickets by wbsCode

src/components/Tickets/Table.js, src/index.css
This full-fills my desire of column totals - https://github.com/nadavspi/UnwiseConnect/issues/44
Show totals of column values for all rows in result pool.
- To enable feature for a row add `showTotals: true` to column declaration.
=> Add new showTotals option to columns and display them in footer table

src/components/Tickets/Table.js
This will right align the values, matching the table data alignment.
=> Add missing budget classname to footer columns

src/components/Tickets/StartTimer.js
Rather than defaulting to the ticket name. This is better for two
reasons:
1. It encourages people to enter a real description instead of lazily using the
name of the ticket.
2. If you already have a timer running in Toggl, clicking Start Timer when
description is empty will append the ticket number to your existing timer.
=> Leave timer description empty by default

src/components/Tickets/ToggleProjects/Projects.js
We don't have an easy method to get to the actual CW project right now. This should ameliorate that some.
=> Add link to CW view in Select Project dropdown

src/components/Tickets/index.js
`.col-md-6` floats elements, which in turn means the (uncleared) sibling ticket table has this element within its box model. This makes pagination's anchor target much higher than it should be.
=> Fix pagination jump on main index

src/components/Dispatch/index.js, src/components/Tickets/Table.js, src/helpers/utils.js
This does two things, which solve problems for me around phase filtering:
1. Filter the full phase path in results, i.e. Dev/Foo/Bar/Baz.  Still displays only Baz, but shows the full path via `title=""`.
2. Allow negative filtering, i.e. `"Sprint 1" -Demo`.  This uses word matching.
To avoid surprises, continues to use phrase matching for searches which don't include hyphen prefixed words (e.g. `Sprint 1` will continue to match the phrase "Sprint 1" instead of "Sprint" and "1".)
=> Search by full phase path and allow negative filters

src/components/Tickets/ToggleProjects/index.js
They're probably the most interesting, after all.
Fixes #30, although it doesn't actually duplicate the active projects within the list (I think it's better not to.)
=> Group all active projects together at the top

src/index.css
Nuance to #83 - we don't want the table headers to have 'hrs' as well
E.g
=> Only append 'hrs' to table data

src/components/Dispatch/index.js
date-fns switched to this.
See: https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table
=> Update format string to use Unicode standard

src/components/Dispatch/Fields/index.js, src/components/Dispatch/index.js, src/components/Tickets/Table.js, src/config/columns.js
Turns out that ConnectWise supports custom fields: https://docs.connectwise.com/ConnectWise_Documentation/090/020/070/038.
This PR add supports for a "Sprint" column. A future PR will add a sprint input to the dispatch form, which the API will use to set the value of the custom field when dispatching.
=> Support Sprint custom field for tickets

src/index.css
[`table-layout: fixed`](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout) allows us to prevent the ticket list table from changing column widths on searches, which can be distracting and costly via a vis performance. The actual speed up from the reduced paint time is not large but it subjectively *feels* quite a bit faster. 
Cells wrap earlier on a fixed layout, which makes long ticket names harder to read. 
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/714017/66263280-e3e85480-e7bd-11e9-90df-6055a57e97be.png) | ![image](https://user-images.githubusercontent.com/714017/66263267-a388d680-e7bd-11e9-9f57-740c2e642694.png) |
This is because each column is now the same size. We'll next need to assign widths to the rows …
=> Speed up search rendering and prevent table from resizing

src/index.css
This way you don't have to scroll the entire page  when navigating the list
=> Cap project list height to show internal scroll

src/components/Dispatch/index.js
Fixes #119
We'll at some point need to use an actual React datepicker for browser compat sake (Safari does not support this), but this switch is at the very least a nice upgrade for Firefox and Chrome users. Unsupported inputs gracefully degrade to a text input, so not a major concern.
Note that the format in this screenshot doesn't match our expected input format (yyyy-mm-dd). That's OK, the seen format != the input value. [From MDN:](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Value)
> **The displayed date format will differ from the actual `value`** — the displayed date is formatted *based on the locale of the user's browser,* but the parsed `value` is always formatted `yyyy-mm-dd`.
=> Switch date dispatch inputs to browser datepickers

src/components/Dispatch/index.js
Adds value 'America/Chicago' as an available timezone so that it will populate  in the timezone dropdown for dispatching
=> Add America/Chicago (Central time) as timezone option

src/components/Dispatch/index.js
Europe/Moscow is frequently used by our contract developers
=> Add Europe/Moscow timezone in dropdown

src/components/Tickets/DetailsModal/index.js
This is likely a clearer metaphor than the new window icon
=> Switch ticket modal button info icon

src/components/Tickets/DetailsModal/ScheduleEntries.js, src/components/Tickets/DetailsModal/TimeEntries.js
Upgrade TimeEntries and SchedulEntries to use React hooks.
Prevents use of deprecated componentWillMount
Fixes issue were loading indicator was not displaying because the state was not set to isLoading: true
Uses &hellip; instead of `. . .` for loading indicator
See issue #130
=> Refactor TimeEntries and ScheduleEntries components to use React hooks

src/index.css
We're using break-word overflow but we're not inserting hyphens. Let's fix that.
=> Add hyphens to ticket tables

package.json, src/components/Tickets/UpdateStatus.js, yarn.lock
Since this component renders for each ticket, it can be very expensive.  Luckily, each ticket gets exactly the same flattened array, so memoize the calculation.
Improves table update performance by ~85%.  It was calculating 180 times, twice, plus a couple extra before on load (and after updating tickets.)  Now it calculates once or twice at most.
=> Memoize the tickets when calculating statuses
