src/components/protected/Tickets/index.js

Add a space before the Add Project caret

---

src/components/Settings/Toggl.js
src/components/Settings/index.js
src/components/Tickets/StartTimer.js

My user was just receiving errors on the Settings page.

Correct Settings handling without toggl prop

---

public/index.html
src/components/Home.js
src/components/Settings/Toggl.js
src/components/Settings/index.js
src/components/Tickets/AddProject.js
src/components/Tickets/Projects.js
src/components/Tickets/Table.js
src/components/Tickets/ToggleProjects/index.js
src/components/Tickets/index.js
src/components/index.js
src/index.css

**Note:** this is my first time contributing any React code – if it sucks, lemme know!
My Saturday project: overhauling UnwiseConnect design and UX. No new functionality here  – this PR focuses instead on (rather subjective) UX/UI changes.
The goal with this one was to simplify to a certain degree the visual hierarchy presented. I deemphasized headers, lowered the visual prominence of the navigation, and floated several elements in an effort to give greater focus to the task list.
From the UX view of a new user to the service, I also added a greeting with some simple copy to the logged out homepage and added a few notes of clarification to some lines of text. I also changed the style (e.g `btn-default` vs `-primary`) of buttons used in a few places to better distinguish the important bits …

UX Changes

---

package.json
src/components/Tickets/Projects.js
src/components/Tickets/ToggleProjects/index.js
src/components/Tickets/index.js
yarn.lock

Sort projects

---

src/components/Tickets/Table.js
src/components/Tickets/TicketLink.js
src/index.css

**Component Hover State**
**Copy Success State (for 500ms following copy)**
Fixes #39

Add button copying ticket number to clipboard

---

src/index.css

* Changes copy success mark to show without hover
* Changes success mark to green
* Shows icon on button focus

Minor ticket ID copy UX changes 

---

src/components/Tickets/index.js

Adding a project by ID will now also toggle it as one of your projects.

Automatically subscribe to a project once added

---

.editorconfig
package.json
src/actions/tickets.js
src/components/Settings/index.js
src/components/Tickets/Table.js
src/components/index.js
yarn.lock

This cleans up a bunch of warnings.  Didn't silence the wrong ones, though.
Also editorconfig.

Fix warnings (like the table resolver one)

---

package.json
src/components/Tickets/SearchColumns.js
src/components/Tickets/Table.js
src/index.css
yarn.lock

This allows selecting multiple statuses in the filter, which was not possible before.

Use a multiselect dropdown for status

---

src/components/Dispatch/Fields/index.js
src/components/Dispatch/Queue.js
src/components/Dispatch/index.js
src/components/Tickets/Pagination.js
src/components/Tickets/Table.js
src/components/Tickets/index.js
src/reducers/tickets.js

Specifically:
* Use multiselect for status (important when switching, and I meant for it to be used here too.)
* Correct pagination jump, instead of jumping to top of page each time.
* Correct visibility toggles mismatch.
* Change button from "Add" to "Remove" on click.
* Prevent rounding errors in total hours.
* Dropdown/typeahead for resource selection.
I'm not sure I did the Add/Remove thing "the right way".  It seems reasonable but I have a sneaky suspicion I should've involved redux...

Dispatching quality of life improvements

---

src/components/Dispatch/index.js
src/components/Tickets/SearchColumns.js

Uses all filtered rows.  Kinda slow currently and duplicates the filtering, so might move the filtered rows to redux perhaps.
Just throwing this up there since I wrote it and doen't want to get it lost.  Perhaps we optimize later.

Allow "Add All" on dispatching page

---

src/actions/tickets.js

Seems some (older projects only?) are missing wbsCode values on some tickets.  Unclear why.

Workaround for missing wbsCode values

---

src/components/Dispatch/index.js
src/components/Tickets/SearchColumns.js
src/components/Tickets/Table.js

Closedish statuses, and everything but.

Add quick status options for common groups

---

package.json
yarn.lock

Greatly improves responsiveness when adding/removing projects.  Should improve loading time too.

Update table-resolver and other dependencies

---

src/actions/user.js
src/components/Dispatch/Fields/index.js
src/components/Dispatch/index.js
src/components/Tickets/Table.js
src/components/Tickets/index.js
src/reducers/user.js

Persist column visibility for each user. 
Fixes issue #9.

Persist column visibility per user

---

src/index.css

Append "hrs" to end of budget cells

---

package.json
src/components/Tickets/DetailsModal.js
src/components/Tickets/IdModal.js
src/components/Tickets/Table.js
src/helpers/cw.js
src/index.css
yarn.lock

Add a button inside the ID column that upon clicking will open a modal containing the notes for that ticket.

Tickets Notes

---

src/index.css

This sets the maximum width of the container to 1300px, up from the previous maximum of 1170px.

Increase maximum width of container

---

package.json
src/actions/budgets.js
src/components/Budgets/CSVExport.js
src/components/Budgets/Item/Form.js
src/components/Budgets/Item/index.js
src/components/Budgets/List.js
src/components/Budgets/MultiSearch.js
src/components/Budgets/Table.js
src/components/Budgets/index.js
src/helpers/reformat.js
src/reducers/budgets.js
yarn.lock

The current branch reverted to budget-tool-redux was not allowing us to rebase the budget-tool-excel-export branch since the commits were already commited to budget-tool-redux.
This revert will restore excel export functionality, but will require us to restore the commits made after the original revert to budget-tool-redux.

Excel export 8/10/2018

---

src/index.css

Turns out that Bootstrap files get loaded later than custom ones?

Increase specificity

---

src/actions/budgets.js
src/components/Budgets/CSVExport.js
src/helpers/reformat.js
src/reducers/budgets.js

Refactor excel sheet footer logic.

Budget tool excel footer

---

package.json
src/components/Budgets/EditColumn.js
src/index.css
yarn.lock

Convert the current iteration of the edit modal from a dropdown type to a react modal component.

Edit modal 8 13 2018

---

src/components/Budgets/index.js

The panel div closed before body causing it to loose the normal styling:
correct:

Fix panel wrapper so it's pretty again

---

package.json
public/index.html
src/actions/tickets.js
src/components/Tickets/ToggleProjects/Projects.css
src/components/Tickets/ToggleProjects/Projects.js
yarn.lock

This shows a relative time (today at 3:00 pm) next to the "Update" button.
As a side effect, it always updates the project name/company name of projects, rather than assuming they never change.

Add last updated time next to projects

---

src/components/Tickets/ToggleProjects/Projects.css

We were losing out to another selector

Fix specificity

---

src/components/Dispatch/index.js
src/components/Tickets/SearchColumns.js
src/index.css

Mostly just what it says on the tin.

Add additional timezones to the dropdown

---

src/components/Budgets/PresetBudgets.js
src/components/Dispatch/index.js
src/components/Tickets/DetailsModal/TimeEntries.js
src/components/Tickets/SearchColumns.js
src/components/Tickets/Table.js
src/helpers/reformat.js
src/reducers/budgets.js

All Open / All Complete should be usable again.

Filter out more statuses, remove option on select

---

src/components/Dispatch/index.js

Specifically for Sprint, for now.

Add custom fields support

---

src/components/Dispatch/Fields/index.js

Permit `date` fields

---

src/components/Tickets/Table.js

Correct overbudget highlighting

---

src/components/Tickets/Table.js

Link to DD tickets

---

.gitignore
README.md
docker-compose.yml.example
src/components/Tickets/ToggleProjects/index.js

Adds a basic text filter for company and project name to the project selection modal.
* Add docker-compose.yml and instructions
* Append key in case of duplicate projects
* Add search filter for selecting projects 
**Search empty**
**Search with term**

Text Filter in Project Selection Modal

---

src/components/Tickets/DetailsModal/Notes.js
src/components/Tickets/DetailsModal/ScheduleEntries.js
src/components/Tickets/DetailsModal/TimeEntries.js
src/components/Tickets/DetailsModal/index.js
src/index.css

This fixes some issues with dates, formats schedule and time entry data in grids. Other minor changes to incrementally improve the UI.
https://share.getcloudapp.com/JruWBW6y

Updates to ticket details modal

---

src/components/Tickets/DetailsModal/Notes.js

Upgrade Notes component to use React hooks.
Prevents use of deprecated componentWillMount
Adds a loading indicator
Adds a message if there are no notes
See issue #130

Refactor Notes component to use React hooks

---

src/components/Tickets/DetailsModal/ScheduleEntries.js
src/components/Tickets/DetailsModal/TimeEntries.js

Adds a sort to Time Entries and Schedule Entries
Closes #175

Sort Ticket Detail Entries in Descending Chronological Order

---

src/components/Dispatch/index.js
src/index.scss

Update tickets from the dispatch portal
